### ISSUE TITLE
Grafana: Database not found; keenetic

### ISSUE THREAD

**Issue by Andrewkha** [vitaliy-sk/keenetic-grafana-monitoring#24]
Hello!

I carefully followed the steps in the readme. Everything seems to be running and no noticeable errors in the container's logs. However grafana dashboard says: "Status: 500. Message: database not found: keenetic" while the connection to the InfluxDB datasource seems to be OK (but no measurements found...)

![image](https://github.com/user-attachments/assets/7e2380ad-1f76-4d63-9e1a-14ee1bf2f1eb)

Seems like some configuration issue, can you please help to troubleshoot?

**Comment by Andrewkha** [comment]
OK, this seems to be resolved, by changing the query language to Flux. However, I do not see the collector adding the data to the DB... Is there a way to ckeck it?

**Comment by cherepavel** [comment]
update influx db to 2.7.11 in docker-compose


![image](https://github.com/user-attachments/assets/6ba2afde-69a0-4657-a265-5fc7d6fb8842)

````
  influxdb:
    image: 'influxdb:2.7.11'
    volumes:
      - ./_data/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=keenetic
      - DOCKER_INFLUXDB_INIT_BUCKET=keenetic
      - DOCKER_INFLUXDB_INIT_RETENTION=52w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin_token
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
````
