### ISSUE TITLE
Wifi clients connected on wifi extenders

### ISSUE THREAD

**Issue by ilker-aktuna** [vitaliy-sk/keenetic-grafana-monitoring#27]
Hi,

I have Keenetic extenders connected to my Keenetic Hero+ router and they are managed by Keenetic Hero+
So I see the wifi clients mostly on these extenders from the main router UI:
![image](https://github.com/user-attachments/assets/2696fe47-8d01-40b2-94a5-6d97e5a85514)

On the collected data, these wifi clients are not shown. There is only signal value for the wifi clients connected to the main router.
However, router can see the signal of other wifi clients which are connected to the extenders.

Is there a way to make these wifi clients' visible as wifi clients ?

**Comment by ilker-aktuna** [comment]
I see that in the "ip hotspot" command output the rssi and mode values of these devices are shown under mws 
as here:
```

host: 
                  mac: 38:42:0b:00:0e:xx
                  via: 38:42:0b:00:0e:xx
                   ip: 192.168.1.21
             hostname: SonosZP
                 name: Sonos One

            interface: 
                       id: Bridge0
                     name: Home
              description: Home network

                 dhcp: 
                   static: yes

           registered: yes
               access: permit
             schedule: 
             priority: 6
               active: yes
              rxbytes: 136678697
              txbytes: 10815655
               uptime: 29986
           first-seen: 599917
            last-seen: 12
                 link: up

                  mws: 
                      cid: 5bcc0f34-ab31-11ed-9396-f7754eed93be
                       ap: WifiMaster0/AccessPoint0
                      psm: no
            authenticated: yes
                   txrate: 173
                   uptime: 29986
                       ht: 20
                     mode: 11n
                       gi: 400
                     rssi: -41
                      mcs: 8
                     txss: 2
                      ebf: no

                      _11: k

                      _11: v

                 security: wpa2-psk

        traffic-shape: 
                       rx: 0
                       tx: 0
                     mode: mac
                 schedule: 


```

so I changed the "ip hotspot" section of my metrics.json:
```

    {
      "command": "ip hotspot",
      "root": "$.host[*]",
      "tags": {
        "hostname": "$.hostname",
        "name": "$.name",
        "ssid": "$.ssid",
        "mode": "$.mode",
        "mwsmode": "$.mws.mode",
        "ip": "$.ip",
        "mac": "$.mac"
      },
      "values": {
        "rxbytes": "$.rxbytes",
        "txbytes": "$.txbytes",
        "txrate": "$.txrate",
        "uptime": "$.uptime",
        "signal": "$.rssi",
        "speed": "$.speed",
        "active": "$.active",
        "signalap": "$.mws.rssi"
      }
    },
```

Now I can get the signal value under "signalap" but the tag displays "undefined" when I use $tag_mwsmode

why ?
